version: '3.1'

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/go/app
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: .env